name: hybrid-threat-env
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - joblib
      - matplotlib
      - seaborn
      - azureml-defaults
channels:
  - defaults
